export const MENTOR_MENTEE_LIST_DESKTOP_INSET = "25px";

export const MENTOR_MENTEE_LIST_VALUE_GRID_TEMPLATE = "80px 112px 72px";

export const MENTOR_MENTEE_LIST_VALUE_GRID_WIDTH = "344px";

export const MENTOR_MENTEE_LIST_DESKTOP_TEMPLATE = `minmax(0, 1fr) ${MENTOR_MENTEE_LIST_VALUE_GRID_WIDTH}`;
